# Generated by Django 6.0.3 on 2026-03-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodentry',
            options={'verbose_name': 'MoodEntry', 'verbose_name_plural': 'MoodEntries'},
        ),
        migrations.AlterModelTable(
            name='moodentry',
            table=None,
        ),
    ]
