# Generated by Django 5.1.4 on 2026-07-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_add_user_id_to_moodentry'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user_id', '-created_at'], name='therapist_userid_created_idx'),
        ),
    ]
