# Generated by Django 6.0.7 on 2026-07-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0004_moodentry_therapist_userid_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='crisis_flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
